### ISSUE TITLE
Suggestion: Changed title color

### ISSUE THREAD

**Issue by edglxyprogramming** [edglxy/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #e49a1a;
}
```
